# Copyright 2021 Touca, Inc. Subject to Apache-2.0 License.

version: "1.4.0.{build}-{branch}"

image:
  - Visual Studio 2019

platform:
  - x64

configuration:
  - Release

before_build:
  - cmd: cmake -B".\local\build" -H"." -G"Visual Studio 16 2019" -A"x64" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DTOUCA_BUILD_TESTS=ON -DTOUCA_BUILD_UTILS=ON -DTOUCA_BUILD_EXAMPLES=ON -DTOUCA_BUILD_FRAMEWORK=ON -DOPENSSL_ROOT_DIR="C:\OpenSSL-v111-Win64"

build:
  project: .\local\build\ALL_BUILD.vcxproj
  parallel: true
  verbosity: normal

after_build:
  - cmd: cmake --install ".\local\build" --prefix ".\local\dist"

test_script:
  - set CTEST_OUTPUT_ON_FAILURE=1
  - cmd: cd "local/build"
  - cmd: ctest . -C Release
